select * from customer limit 20;


--Q1. What is the total revenue generated by male vs. female customers?

select "Gender", SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender";


--Q2. Which customers used a discount but still spent more than the average amount?

select "Customer ID", "Purchase Amount (USD)"
from customer
where "Discount Applied" = 'Yes' 
  and "Purchase Amount (USD)" > (select AVG("Purchase Amount (USD)") from customer);
  

--Q3. Which are the top 5 products with the highest average review rating?

select "Item Purchased", AVG("Review Rating") as avg_rating
from customer
group by "Item Purchased"
order by avg_rating DESC
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

 select "Shipping Type", AVG("Purchase Amount (USD)") as avg_purchase
from customer
where "Shipping Type" IN ('Standard', 'Express')
group by "Shipping Type";


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select 
    "Subscription Status", 
    AVG("Purchase Amount (USD)") as avg_spend,
    SUM("Purchase Amount (USD)") as total_revenue
from customer
group by "Subscription Status";



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select 
    "Item Purchased",
    COUNT(case when "Discount Applied" = 'Yes' then 1 end) * 100.0 / COUNT(*) as discount_percentage==
from customer
group by "Item Purchased"
order by discount_percentage DESC
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select 
    case 
        when "Previous Purchases" = 1 then 'New'
        when "Previous Purchases" between 2 and 10 then 'Returning'
        else 'Loyal'
    end as customer_segment,
    COUNT(*) as customer_count
from customer
group by 
    case 
        when "Previous Purchases" = 1 then 'New'
        when "Previous Purchases" between 2 and 10 then 'Returning'
        else 'Loyal'
    end;

	

--Q8. What are the top 3 most purchased products within each category?

with ranked_products as (
    select 
        "Category",
        "Item Purchased",
        COUNT(*) as purchase_count,
        ROW_NUMBER() over(partition by "Category" order by COUNT(*) DESC) as rank
    from customer
    group by "Category", "Item Purchased"
)
select "Category", "Item Purchased", purchase_count
from ranked_products
where rank <= 3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely subscribe?

select 
    "Subscription Status",
    COUNT("Customer ID") as repeat_buyers
from customer
where "Previous Purchases" > 5
group by "Subscription Status";

--Q10. What is the revenue contribution of each age group?===========\

select 
    case 
        when "Age" between 18 and 25 then 'Young Adult'
        when "Age" between 26 and 35 then 'Middle-aged'
        when "Age" between 36 and 50 then 'Adult'
        else 'Senior'
    end as age_group,
    SUM("Purchase Amount (USD)") as total_revenue
from customer
group by 
    case 
        when "Age" between 18 and 25 then 'Young Adult'
        when "Age" between 26 and 35 then 'Middle-aged'
        when "Age" between 36 and 50 then 'Adult'
        else 'Senior'
    end
order by total_revenue desc;